### ISSUE TITLE
Please reconsider cli-based macos tools

### ISSUE THREAD

**Issue by hasuf** [Snirpo/aawireless-dram-fix#2]
Hi,

I understand the sentiment that there are users that may not be able to use these advanced tools, but there are many people like myself that know  their way around homebrew and the command line.

For instance, many companies like ours issue macs to their dev teams for development because of Darwin's unix-based heritage. 

I was able to piece together the mac instructions from the commit that removed the mac-related files (https://github.com/Snirpo/aawireless-dram-fix/commit/3dd9b0d2c0068305b2541297817710658f5a7f42) and flash my device. Please reconsider the addition of the cli-based mac tools for advanced users.

Thanks,

-- joseph

**Comment by Snirpo** [comment]
I've reverted the commit, it's back again.
