### ISSUE TITLE
Windows bat: error messages might confuse people

### ISSUE THREAD

**Issue by andrewleech** [Snirpo/aawireless-dram-fix#3]
Fantastic work getting an easy to use patch kit out so quick, nice work. A little feedback; I had some error messages show immediately after getting my unit into flash mode (second attempt, first attempt I held button too long)
```
Please plug the AAWireless device into a USB port now. You will need to get AAWireless in 'Flash mode'
Push and hold the reset button on your AAWireless device with a pin for about 10 seconds then release.
Hold the button for too long or too short and it will not go into 'Flash mode'.
When counting silently, a count of 12 to 14 is often right.
You will know you are in Flash mode when the LED goes off.
It will not flash or be any solid color when in 'Flash mode'
If the timing is not right, you may have to try multiple times to get it into 'Flash mode'
Waiting for AAWireless device 'Flash mode'
←[30;41mCreating Comm Object failed!←[0m
Waiting for device to re-enumerate
Write LBA quit, creating comm object failed!
Reset Device quit, creating comm object failed!
Device patched successfully, you can now use the device.
Press any key to continue . . .
```

Based on a the `Device patched successfully` I'm assuming it got there in the end and the previous error messages were just while polling for the device to be started enough to accept the communication, however these messages might be quite alarming for less technical users.

Thanks for the hard work!

**Comment by Snirpo** [comment]
No it actually failed :( Please hold on cause we are questioning ourselves of this is the right way to push this patch.

**Comment by andrewleech** [comment]
Ah, thanks for the reply. fwiw I'm an embedded fw&elec engineer with low level android hacking experience - I'm more than happy to help if there's anything I can assist in.

**Comment by andrewleech** [comment]
Hi, I did get the OTA and it installed smoothly for me. Thanks again for the great work!
