### ISSUE TITLE
The reset button gave in and broke

### ISSUE THREAD

**Issue by pauloargue** [Snirpo/aawireless-dram-fix#4]
Is there a fix or otherwise another option for flashing without using the reset button?  My reset button gave in on first go.

My unit won't connect to Android Auto and I believe it's second batch unit.

**Comment by Snirpo** [comment]
No unfortunately not. Please contact support for a replacement unit. However if you want to test if this fixes your issues (if you have any) you can update to version 1.2.3 via the companion app, this version includes this "DRAM" fix.
