### ISSUE TITLE
What IDs need to flash

### ISSUE THREAD

**Issue by Martinspire** [Snirpo/aawireless-dram-fix#5]
Hi there,

It would be helpful if there was a list somewhere in this repo that indicates whether folks should flash or not. The communication talks about batch 1, 2 and 3+ but it never really said who has their device in these batches.

I'm contribution number 1920 myself, I think I might be in the first or second batch but I simply can't remember.

Thanks,
Martin

**Comment by Snirpo** [comment]
In general you don't need to use this tool:

Please first try to OTA update to version 1.2.3, then you don't need this fix anymore. Only use this tool if the device is too unstable to be able to apply the OTA update.
